import {
  type BacklinkDTO,
  type InternalLinkRefDTO,
  type NoteDTO,
  type NoteListItemDTO,
  toInternalLinkRefDTO,
  toNoteDTO,
} from "@/core/application/dto";
import type { Note } from "@/core/domain/note/entity";
import type { HtmlSanitizer } from "@/core/domain/note/ports/htmlSanitizer";

export type { BacklinkDTO, InternalLinkRefDTO, NoteDTO, NoteListItemDTO };

/**
 * Project a `Note` aggregate to its `NoteDTO` wire shape. Thin wrapper
 * over the common DTO helper so usecases in this module can `import {
 * toNoteView }` for symmetry with `toTodoView` etc.
 */
export const toNoteView = (note: Note): NoteDTO => toNoteDTO(note);

/**
 * Build the listing-projection of `Note` for owner-scoped queries.
 * `excerpt` / `tagNames` / `visibility` are not carried by the aggregate;
 * callers supply them from the surrounding listing pipeline (tag-name
 * join, sanitized excerpt, publication state).
 */
export function toNoteListItem(
  note: Note,
  context: Readonly<{
    excerpt: string;
    tagNames: readonly string[];
    visibility: "private" | "unlisted" | "public";
  }>,
): NoteListItemDTO {
  return {
    id: note.id,
    ownerId: note.ownerId,
    directoryId: note.directoryId,
    slug: note.slug,
    title: note.title,
    excerpt: context.excerpt,
    tagIds: note.tagIds,
    tagNames: context.tagNames,
    updatedAt: note.updatedAt.toISOString(),
    visibility: context.visibility,
  };
}

/**
 * Backlink projection for `GetBacklinks` / `GetNoteDetail`. The source
 * `Note` is always an active referrer; trashed notes are filtered out by
 * the repository. `snippet` is a plain-text excerpt of the referrer body
 * generated by the caller (`null` when empty).
 */
export function toBacklink(
  note: Note,
  context: Readonly<{ snippet: string | null }>,
): BacklinkDTO {
  return {
    noteId: note.id,
    title: note.title,
    slug: note.slug,
    snippet: context.snippet,
  };
}

/**
 * Plain-text excerpt of a backlink referrer body, capped at 200 chars.
 * Returns `null` when the body sanitises to an empty string so callers
 * can collapse it uniformly across `GetNoteDetail` / `GetBacklinks`.
 */
export function buildBacklinkSnippet(
  htmlSanitizer: HtmlSanitizer,
  note: Note,
): string | null {
  const text = htmlSanitizer.toPlainText(note.contentHtml).slice(0, 200);
  return text.length > 0 ? text : null;
}

export { toInternalLinkRefDTO, toNoteDTO };
