config:
  hollow:appName: hollow
  hollow:stage: staging
  hollow:zoneName: maku-ja.com
  hollow:hostname: staging.hollow.maku-ja.com
  hollow:emailFrom: noreply@maku-ja.com
  hollow:cloudflareAccountId: 5ca5e9b7a94fd68cb165f0c9151343b9
  hollow:llmProvider: gemini
  hollow:llmModel: gemini-2.5-flash
  hollow:llmBaseUrl: ""
