export const IdentityErrorCode = {
  InvalidUserId: "user_invalid_id",
  InvalidUsername: "username_invalid",
  UsernameTooShort: "username_too_short",
  UsernameTooLong: "username_too_long",
  UsernameReserved: "username_reserved",
  InvalidEmail: "email_invalid",
  EmailTooLong: "email_too_long",
  PasswordTooShort: "password_too_short",
  PasswordTooLong: "password_too_long",
  PasswordInsufficientVariety: "password_insufficient_variety",
  InvalidPasswordHash: "password_hash_invalid",
  InvalidUserStatus: "user_invalid_status",
  InvalidRole: "user_invalid_role",
  InvalidChallengePurpose: "challenge_invalid_purpose",
  InvalidCredentialKind: "credential_invalid_kind",
  InvalidMediaAssetId: "media_asset_id_invalid",
  DisplayNameEmpty: "display_name_empty",
  DisplayNameTooLong: "display_name_too_long",
  BioTooLong: "bio_too_long",

  UserNotPending: "user_not_pending",
  UserNotActive: "user_not_active",
  UserNotSuspended: "user_not_suspended",
  AlreadyDeleted: "already_deleted",
  AlreadyAdmin: "already_admin",
  AlreadyMember: "already_member",
  UsernameChangeTooSoon: "username_change_too_soon",
  UsernameTaken: "username_taken",
  EmailTaken: "email_taken",
  LastAdminProtected: "last_admin_protected",
  NoCredentialRemaining: "no_credential_remaining",
  CannotRemoveLastCredential: "cannot_remove_last_credential",
  PasswordAlreadySet: "password_already_set",
  ProviderAlreadyLinked: "provider_already_linked",
  TokenNotFound: "token_not_found",
  TokenExpired: "token_expired",
  TokenConsumed: "token_consumed",
  TokenPurposeMismatch: "token_purpose_mismatch",
  MediaNotOwned: "media_not_owned",
} as const;

export type IdentityErrorCode =
  (typeof IdentityErrorCode)[keyof typeof IdentityErrorCode];
