export const IdentityErrorCode = {
  InvalidUserId: "USER_INVALID_ID",
  InvalidUsername: "USERNAME_INVALID",
  UsernameTooShort: "USERNAME_TOO_SHORT",
  UsernameTooLong: "USERNAME_TOO_LONG",
  UsernameReserved: "USERNAME_RESERVED",
  InvalidEmail: "EMAIL_INVALID",
  EmailTooLong: "EMAIL_TOO_LONG",
  PasswordTooShort: "PASSWORD_TOO_SHORT",
  PasswordTooLong: "PASSWORD_TOO_LONG",
  PasswordInsufficientVariety: "PASSWORD_INSUFFICIENT_VARIETY",
  InvalidPasswordHash: "PASSWORD_HASH_INVALID",
  InvalidUserStatus: "USER_INVALID_STATUS",
  InvalidRole: "USER_INVALID_ROLE",
  InvalidChallengePurpose: "CHALLENGE_INVALID_PURPOSE",
  InvalidCredentialKind: "CREDENTIAL_INVALID_KIND",
  InvalidMediaAssetId: "MEDIA_ASSET_ID_INVALID",
  DisplayNameEmpty: "DISPLAY_NAME_EMPTY",
  DisplayNameTooLong: "DISPLAY_NAME_TOO_LONG",
  BioTooLong: "BIO_TOO_LONG",

  UserNotPending: "user_not_pending",
  UserNotActive: "user_not_active",
  UserNotSuspended: "user_not_suspended",
  AlreadyDeleted: "already_deleted",
  AlreadyAdmin: "already_admin",
  AlreadyMember: "already_member",
  UsernameChangeTooSoon: "username_change_too_soon",
  UsernameTaken: "username_taken",
  EmailTaken: "email_taken",
  LastAdminProtected: "last_admin_protected",
  NoCredentialRemaining: "no_credential_remaining",
  CannotRemoveLastCredential: "cannot_remove_last_credential",
  PasswordAlreadySet: "password_already_set",
  ProviderAlreadyLinked: "provider_already_linked",
} as const;

export type IdentityErrorCode =
  (typeof IdentityErrorCode)[keyof typeof IdentityErrorCode];
