/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AboutRouteImport } from './routes/about'
import { Route as URouteRouteImport } from './routes/u/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PasswordResetIndexRouteImport } from './routes/password-reset/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as PasswordResetConfirmRouteImport } from './routes/password-reset/confirm'
import { Route as MediaMediaIdRouteImport } from './routes/media/$mediaId'
import { Route as EmailChangeConfirmRouteImport } from './routes/email-change/confirm'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSpeechRouteImport } from './routes/admin/speech'
import { Route as AdminRegistrationRouteImport } from './routes/admin/registration'
import { Route as AdminPromptsRouteImport } from './routes/admin/prompts'
import { Route as AdminMetricsRouteImport } from './routes/admin/metrics'
import { Route as AdminLlmRouteImport } from './routes/admin/llm'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminDesignRouteImport } from './routes/admin/design'
import { Route as AppViewsRouteRouteImport } from './routes/_app/views/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppExportsRouteRouteImport } from './routes/_app/exports/route'
import { Route as UUsernameIndexRouteImport } from './routes/u/$username/index'
import { Route as AppViewsIndexRouteImport } from './routes/_app/views/index'
import { Route as AppUploadIndexRouteImport } from './routes/_app/upload/index'
import { Route as AppTrashIndexRouteImport } from './routes/_app/trash/index'
import { Route as AppTagsIndexRouteImport } from './routes/_app/tags/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppExportsIndexRouteImport } from './routes/_app/exports/index'
import { Route as AppExportIndexRouteImport } from './routes/_app/export/index'
import { Route as UUsernameNoteSlugRouteImport } from './routes/u/$username/$noteSlug'
import { Route as NotesPublicNoteIdRouteImport } from './routes/notes/public/$noteId'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'
import { Route as AppSettingsPromptsRouteImport } from './routes/_app/settings/prompts'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsAccountDeleteRouteImport } from './routes/_app/settings/account-delete'
import { Route as AppNotesNewRouteImport } from './routes/_app/notes/new'
import { Route as AppExportsJobIdRouteImport } from './routes/_app/exports/$jobId'
import { Route as AppNotesNoteIdIndexRouteImport } from './routes/_app/notes/$noteId/index'
import { Route as AppNotesNoteIdExportRouteImport } from './routes/_app/notes/$noteId/export'
import { Route as AppNotesNoteIdEditRouteImport } from './routes/_app/notes/$noteId/edit'
import { Route as AppNotesNoteIdHistoryRouteRouteImport } from './routes/_app/notes/$noteId/history/route'
import { Route as AppNotesNoteIdHistoryIndexRouteImport } from './routes/_app/notes/$noteId/history/index'
import { Route as AppNotesNoteIdHistoryRevisionIdRouteImport } from './routes/_app/notes/$noteId/history/$revisionId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const URouteRoute = URouteRouteImport.update({
  id: '/u',
  path: '/u',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetIndexRoute = PasswordResetIndexRouteImport.update({
  id: '/password-reset/',
  path: '/password-reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetConfirmRoute = PasswordResetConfirmRouteImport.update({
  id: '/password-reset/confirm',
  path: '/password-reset/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaMediaIdRoute = MediaMediaIdRouteImport.update({
  id: '/media/$mediaId',
  path: '/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailChangeConfirmRoute = EmailChangeConfirmRouteImport.update({
  id: '/email-change/confirm',
  path: '/email-change/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSpeechRoute = AdminSpeechRouteImport.update({
  id: '/speech',
  path: '/speech',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegistrationRoute = AdminRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromptsRoute = AdminPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLlmRoute = AdminLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDesignRoute = AdminDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppViewsRouteRoute = AppViewsRouteRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExportsRouteRoute = AppExportsRouteRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRouteRoute,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => URouteRoute,
} as any)
const AppViewsIndexRoute = AppViewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppViewsRouteRoute,
} as any)
const AppUploadIndexRoute = AppUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrashIndexRoute = AppTrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTagsIndexRoute = AppTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppExportsIndexRoute = AppExportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExportsRouteRoute,
} as any)
const AppExportIndexRoute = AppExportIndexRouteImport.update({
  id: '/export/',
  path: '/export/',
  getParentRoute: () => AppRouteRoute,
} as any)
const UUsernameNoteSlugRoute = UUsernameNoteSlugRouteImport.update({
  id: '/$username/$noteSlug',
  path: '/$username/$noteSlug',
  getParentRoute: () => URouteRoute,
} as any)
const NotesPublicNoteIdRoute = NotesPublicNoteIdRouteImport.update({
  id: '/notes/public/$noteId',
  path: '/notes/public/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsPromptsRoute = AppSettingsPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAccountDeleteRoute =
  AppSettingsAccountDeleteRouteImport.update({
    id: '/account-delete',
    path: '/account-delete',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppNotesNewRoute = AppNotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExportsJobIdRoute = AppExportsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppExportsRouteRoute,
} as any)
const AppNotesNoteIdIndexRoute = AppNotesNoteIdIndexRouteImport.update({
  id: '/notes/$noteId/',
  path: '/notes/$noteId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdExportRoute = AppNotesNoteIdExportRouteImport.update({
  id: '/notes/$noteId/export',
  path: '/notes/$noteId/export',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdEditRoute = AppNotesNoteIdEditRouteImport.update({
  id: '/notes/$noteId/edit',
  path: '/notes/$noteId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdHistoryRouteRoute =
  AppNotesNoteIdHistoryRouteRouteImport.update({
    id: '/notes/$noteId/history',
    path: '/notes/$noteId/history',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppNotesNoteIdHistoryIndexRoute =
  AppNotesNoteIdHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppNotesNoteIdHistoryRouteRoute,
  } as any)
const AppNotesNoteIdHistoryRevisionIdRoute =
  AppNotesNoteIdHistoryRevisionIdRouteImport.update({
    id: '/$revisionId',
    path: '/$revisionId',
    getParentRoute: () => AppNotesNoteIdHistoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/exports': typeof AppExportsRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/views': typeof AppViewsRouteRouteWithChildren
  '/admin/design': typeof AdminDesignRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/registration': typeof AdminRegistrationRoute
  '/admin/speech': typeof AdminSpeechRoute
  '/admin/users': typeof AdminUsersRoute
  '/email-change/confirm': typeof EmailChangeConfirmRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/exports/$jobId': typeof AppExportsJobIdRoute
  '/notes/new': typeof AppNotesNewRoute
  '/settings/account-delete': typeof AppSettingsAccountDeleteRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/prompts': typeof AppSettingsPromptsRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/notes/public/$noteId': typeof NotesPublicNoteIdRoute
  '/u/$username/$noteSlug': typeof UUsernameNoteSlugRoute
  '/export/': typeof AppExportIndexRoute
  '/exports/': typeof AppExportsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tags/': typeof AppTagsIndexRoute
  '/trash/': typeof AppTrashIndexRoute
  '/upload/': typeof AppUploadIndexRoute
  '/views/': typeof AppViewsIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/notes/$noteId/history': typeof AppNotesNoteIdHistoryRouteRouteWithChildren
  '/notes/$noteId/edit': typeof AppNotesNoteIdEditRoute
  '/notes/$noteId/export': typeof AppNotesNoteIdExportRoute
  '/notes/$noteId/': typeof AppNotesNoteIdIndexRoute
  '/notes/$noteId/history/$revisionId': typeof AppNotesNoteIdHistoryRevisionIdRoute
  '/notes/$noteId/history/': typeof AppNotesNoteIdHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/u': typeof URouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/registration': typeof AdminRegistrationRoute
  '/admin/speech': typeof AdminSpeechRoute
  '/admin/users': typeof AdminUsersRoute
  '/email-change/confirm': typeof EmailChangeConfirmRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/password-reset': typeof PasswordResetIndexRoute
  '/exports/$jobId': typeof AppExportsJobIdRoute
  '/notes/new': typeof AppNotesNewRoute
  '/settings/account-delete': typeof AppSettingsAccountDeleteRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/prompts': typeof AppSettingsPromptsRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/notes/public/$noteId': typeof NotesPublicNoteIdRoute
  '/u/$username/$noteSlug': typeof UUsernameNoteSlugRoute
  '/export': typeof AppExportIndexRoute
  '/exports': typeof AppExportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tags': typeof AppTagsIndexRoute
  '/trash': typeof AppTrashIndexRoute
  '/upload': typeof AppUploadIndexRoute
  '/views': typeof AppViewsIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/notes/$noteId/edit': typeof AppNotesNoteIdEditRoute
  '/notes/$noteId/export': typeof AppNotesNoteIdExportRoute
  '/notes/$noteId': typeof AppNotesNoteIdIndexRoute
  '/notes/$noteId/history/$revisionId': typeof AppNotesNoteIdHistoryRevisionIdRoute
  '/notes/$noteId/history': typeof AppNotesNoteIdHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/exports': typeof AppExportsRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/views': typeof AppViewsRouteRouteWithChildren
  '/admin/design': typeof AdminDesignRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/registration': typeof AdminRegistrationRoute
  '/admin/speech': typeof AdminSpeechRoute
  '/admin/users': typeof AdminUsersRoute
  '/email-change/confirm': typeof EmailChangeConfirmRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/_app/exports/$jobId': typeof AppExportsJobIdRoute
  '/_app/notes/new': typeof AppNotesNewRoute
  '/_app/settings/account-delete': typeof AppSettingsAccountDeleteRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/prompts': typeof AppSettingsPromptsRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/notes/public/$noteId': typeof NotesPublicNoteIdRoute
  '/u/$username/$noteSlug': typeof UUsernameNoteSlugRoute
  '/_app/export/': typeof AppExportIndexRoute
  '/_app/exports/': typeof AppExportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tags/': typeof AppTagsIndexRoute
  '/_app/trash/': typeof AppTrashIndexRoute
  '/_app/upload/': typeof AppUploadIndexRoute
  '/_app/views/': typeof AppViewsIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/_app/notes/$noteId/history': typeof AppNotesNoteIdHistoryRouteRouteWithChildren
  '/_app/notes/$noteId/edit': typeof AppNotesNoteIdEditRoute
  '/_app/notes/$noteId/export': typeof AppNotesNoteIdExportRoute
  '/_app/notes/$noteId/': typeof AppNotesNoteIdIndexRoute
  '/_app/notes/$noteId/history/$revisionId': typeof AppNotesNoteIdHistoryRevisionIdRoute
  '/_app/notes/$noteId/history/': typeof AppNotesNoteIdHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/u'
    | '/about'
    | '/error'
    | '/login'
    | '/privacy'
    | '/search'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/exports'
    | '/settings'
    | '/views'
    | '/admin/design'
    | '/admin/jobs'
    | '/admin/llm'
    | '/admin/metrics'
    | '/admin/prompts'
    | '/admin/registration'
    | '/admin/speech'
    | '/admin/users'
    | '/email-change/confirm'
    | '/media/$mediaId'
    | '/password-reset/confirm'
    | '/share/$token'
    | '/admin/'
    | '/password-reset/'
    | '/exports/$jobId'
    | '/notes/new'
    | '/settings/account-delete'
    | '/settings/profile'
    | '/settings/prompts'
    | '/settings/security'
    | '/notes/public/$noteId'
    | '/u/$username/$noteSlug'
    | '/export/'
    | '/exports/'
    | '/settings/'
    | '/tags/'
    | '/trash/'
    | '/upload/'
    | '/views/'
    | '/u/$username/'
    | '/notes/$noteId/history'
    | '/notes/$noteId/edit'
    | '/notes/$noteId/export'
    | '/notes/$noteId/'
    | '/notes/$noteId/history/$revisionId'
    | '/notes/$noteId/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/u'
    | '/about'
    | '/error'
    | '/login'
    | '/privacy'
    | '/search'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/design'
    | '/admin/jobs'
    | '/admin/llm'
    | '/admin/metrics'
    | '/admin/prompts'
    | '/admin/registration'
    | '/admin/speech'
    | '/admin/users'
    | '/email-change/confirm'
    | '/media/$mediaId'
    | '/password-reset/confirm'
    | '/share/$token'
    | '/'
    | '/admin'
    | '/password-reset'
    | '/exports/$jobId'
    | '/notes/new'
    | '/settings/account-delete'
    | '/settings/profile'
    | '/settings/prompts'
    | '/settings/security'
    | '/notes/public/$noteId'
    | '/u/$username/$noteSlug'
    | '/export'
    | '/exports'
    | '/settings'
    | '/tags'
    | '/trash'
    | '/upload'
    | '/views'
    | '/u/$username'
    | '/notes/$noteId/edit'
    | '/notes/$noteId/export'
    | '/notes/$noteId'
    | '/notes/$noteId/history/$revisionId'
    | '/notes/$noteId/history'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/u'
    | '/about'
    | '/error'
    | '/login'
    | '/privacy'
    | '/search'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/_app/exports'
    | '/_app/settings'
    | '/_app/views'
    | '/admin/design'
    | '/admin/jobs'
    | '/admin/llm'
    | '/admin/metrics'
    | '/admin/prompts'
    | '/admin/registration'
    | '/admin/speech'
    | '/admin/users'
    | '/email-change/confirm'
    | '/media/$mediaId'
    | '/password-reset/confirm'
    | '/share/$token'
    | '/_app/'
    | '/admin/'
    | '/password-reset/'
    | '/_app/exports/$jobId'
    | '/_app/notes/new'
    | '/_app/settings/account-delete'
    | '/_app/settings/profile'
    | '/_app/settings/prompts'
    | '/_app/settings/security'
    | '/notes/public/$noteId'
    | '/u/$username/$noteSlug'
    | '/_app/export/'
    | '/_app/exports/'
    | '/_app/settings/'
    | '/_app/tags/'
    | '/_app/trash/'
    | '/_app/upload/'
    | '/_app/views/'
    | '/u/$username/'
    | '/_app/notes/$noteId/history'
    | '/_app/notes/$noteId/edit'
    | '/_app/notes/$noteId/export'
    | '/_app/notes/$noteId/'
    | '/_app/notes/$noteId/history/$revisionId'
    | '/_app/notes/$noteId/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  URouteRoute: typeof URouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EmailChangeConfirmRoute: typeof EmailChangeConfirmRoute
  MediaMediaIdRoute: typeof MediaMediaIdRoute
  PasswordResetConfirmRoute: typeof PasswordResetConfirmRoute
  ShareTokenRoute: typeof ShareTokenRoute
  PasswordResetIndexRoute: typeof PasswordResetIndexRoute
  NotesPublicNoteIdRoute: typeof NotesPublicNoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u': {
      id: '/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof URouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/': {
      id: '/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset/'
      preLoaderRoute: typeof PasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/confirm': {
      id: '/password-reset/confirm'
      path: '/password-reset/confirm'
      fullPath: '/password-reset/confirm'
      preLoaderRoute: typeof PasswordResetConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$mediaId': {
      id: '/media/$mediaId'
      path: '/media/$mediaId'
      fullPath: '/media/$mediaId'
      preLoaderRoute: typeof MediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-change/confirm': {
      id: '/email-change/confirm'
      path: '/email-change/confirm'
      fullPath: '/email-change/confirm'
      preLoaderRoute: typeof EmailChangeConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/speech': {
      id: '/admin/speech'
      path: '/speech'
      fullPath: '/admin/speech'
      preLoaderRoute: typeof AdminSpeechRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration': {
      id: '/admin/registration'
      path: '/registration'
      fullPath: '/admin/registration'
      preLoaderRoute: typeof AdminRegistrationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/prompts': {
      id: '/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminPromptsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/llm': {
      id: '/admin/llm'
      path: '/llm'
      fullPath: '/admin/llm'
      preLoaderRoute: typeof AdminLlmRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/design': {
      id: '/admin/design'
      path: '/design'
      fullPath: '/admin/design'
      preLoaderRoute: typeof AdminDesignRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/views': {
      id: '/_app/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof AppViewsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof URouteRoute
    }
    '/_app/views/': {
      id: '/_app/views/'
      path: '/'
      fullPath: '/views/'
      preLoaderRoute: typeof AppViewsIndexRouteImport
      parentRoute: typeof AppViewsRouteRoute
    }
    '/_app/upload/': {
      id: '/_app/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof AppUploadIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/trash/': {
      id: '/_app/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof AppTrashIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tags/': {
      id: '/_app/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AppTagsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/exports/': {
      id: '/_app/exports/'
      path: '/'
      fullPath: '/exports/'
      preLoaderRoute: typeof AppExportsIndexRouteImport
      parentRoute: typeof AppExportsRouteRoute
    }
    '/_app/export/': {
      id: '/_app/export/'
      path: '/export'
      fullPath: '/export/'
      preLoaderRoute: typeof AppExportIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/u/$username/$noteSlug': {
      id: '/u/$username/$noteSlug'
      path: '/$username/$noteSlug'
      fullPath: '/u/$username/$noteSlug'
      preLoaderRoute: typeof UUsernameNoteSlugRouteImport
      parentRoute: typeof URouteRoute
    }
    '/notes/public/$noteId': {
      id: '/notes/public/$noteId'
      path: '/notes/public/$noteId'
      fullPath: '/notes/public/$noteId'
      preLoaderRoute: typeof NotesPublicNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/prompts': {
      id: '/_app/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof AppSettingsPromptsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/account-delete': {
      id: '/_app/settings/account-delete'
      path: '/account-delete'
      fullPath: '/settings/account-delete'
      preLoaderRoute: typeof AppSettingsAccountDeleteRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/notes/new': {
      id: '/_app/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AppNotesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/exports/$jobId': {
      id: '/_app/exports/$jobId'
      path: '/$jobId'
      fullPath: '/exports/$jobId'
      preLoaderRoute: typeof AppExportsJobIdRouteImport
      parentRoute: typeof AppExportsRouteRoute
    }
    '/_app/notes/$noteId/': {
      id: '/_app/notes/$noteId/'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId/'
      preLoaderRoute: typeof AppNotesNoteIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId/export': {
      id: '/_app/notes/$noteId/export'
      path: '/notes/$noteId/export'
      fullPath: '/notes/$noteId/export'
      preLoaderRoute: typeof AppNotesNoteIdExportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId/edit': {
      id: '/_app/notes/$noteId/edit'
      path: '/notes/$noteId/edit'
      fullPath: '/notes/$noteId/edit'
      preLoaderRoute: typeof AppNotesNoteIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId/history': {
      id: '/_app/notes/$noteId/history'
      path: '/notes/$noteId/history'
      fullPath: '/notes/$noteId/history'
      preLoaderRoute: typeof AppNotesNoteIdHistoryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId/history/': {
      id: '/_app/notes/$noteId/history/'
      path: '/'
      fullPath: '/notes/$noteId/history/'
      preLoaderRoute: typeof AppNotesNoteIdHistoryIndexRouteImport
      parentRoute: typeof AppNotesNoteIdHistoryRouteRoute
    }
    '/_app/notes/$noteId/history/$revisionId': {
      id: '/_app/notes/$noteId/history/$revisionId'
      path: '/$revisionId'
      fullPath: '/notes/$noteId/history/$revisionId'
      preLoaderRoute: typeof AppNotesNoteIdHistoryRevisionIdRouteImport
      parentRoute: typeof AppNotesNoteIdHistoryRouteRoute
    }
  }
}

interface AppExportsRouteRouteChildren {
  AppExportsJobIdRoute: typeof AppExportsJobIdRoute
  AppExportsIndexRoute: typeof AppExportsIndexRoute
}

const AppExportsRouteRouteChildren: AppExportsRouteRouteChildren = {
  AppExportsJobIdRoute: AppExportsJobIdRoute,
  AppExportsIndexRoute: AppExportsIndexRoute,
}

const AppExportsRouteRouteWithChildren = AppExportsRouteRoute._addFileChildren(
  AppExportsRouteRouteChildren,
)

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountDeleteRoute: typeof AppSettingsAccountDeleteRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsPromptsRoute: typeof AppSettingsPromptsRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountDeleteRoute: AppSettingsAccountDeleteRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsPromptsRoute: AppSettingsPromptsRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppViewsRouteRouteChildren {
  AppViewsIndexRoute: typeof AppViewsIndexRoute
}

const AppViewsRouteRouteChildren: AppViewsRouteRouteChildren = {
  AppViewsIndexRoute: AppViewsIndexRoute,
}

const AppViewsRouteRouteWithChildren = AppViewsRouteRoute._addFileChildren(
  AppViewsRouteRouteChildren,
)

interface AppNotesNoteIdHistoryRouteRouteChildren {
  AppNotesNoteIdHistoryRevisionIdRoute: typeof AppNotesNoteIdHistoryRevisionIdRoute
  AppNotesNoteIdHistoryIndexRoute: typeof AppNotesNoteIdHistoryIndexRoute
}

const AppNotesNoteIdHistoryRouteRouteChildren: AppNotesNoteIdHistoryRouteRouteChildren =
  {
    AppNotesNoteIdHistoryRevisionIdRoute: AppNotesNoteIdHistoryRevisionIdRoute,
    AppNotesNoteIdHistoryIndexRoute: AppNotesNoteIdHistoryIndexRoute,
  }

const AppNotesNoteIdHistoryRouteRouteWithChildren =
  AppNotesNoteIdHistoryRouteRoute._addFileChildren(
    AppNotesNoteIdHistoryRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppExportsRouteRoute: typeof AppExportsRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppViewsRouteRoute: typeof AppViewsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppNotesNewRoute: typeof AppNotesNewRoute
  AppExportIndexRoute: typeof AppExportIndexRoute
  AppTagsIndexRoute: typeof AppTagsIndexRoute
  AppTrashIndexRoute: typeof AppTrashIndexRoute
  AppUploadIndexRoute: typeof AppUploadIndexRoute
  AppNotesNoteIdHistoryRouteRoute: typeof AppNotesNoteIdHistoryRouteRouteWithChildren
  AppNotesNoteIdEditRoute: typeof AppNotesNoteIdEditRoute
  AppNotesNoteIdExportRoute: typeof AppNotesNoteIdExportRoute
  AppNotesNoteIdIndexRoute: typeof AppNotesNoteIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppExportsRouteRoute: AppExportsRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppViewsRouteRoute: AppViewsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppNotesNewRoute: AppNotesNewRoute,
  AppExportIndexRoute: AppExportIndexRoute,
  AppTagsIndexRoute: AppTagsIndexRoute,
  AppTrashIndexRoute: AppTrashIndexRoute,
  AppUploadIndexRoute: AppUploadIndexRoute,
  AppNotesNoteIdHistoryRouteRoute: AppNotesNoteIdHistoryRouteRouteWithChildren,
  AppNotesNoteIdEditRoute: AppNotesNoteIdEditRoute,
  AppNotesNoteIdExportRoute: AppNotesNoteIdExportRoute,
  AppNotesNoteIdIndexRoute: AppNotesNoteIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminDesignRoute: typeof AdminDesignRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLlmRoute: typeof AdminLlmRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminPromptsRoute: typeof AdminPromptsRoute
  AdminRegistrationRoute: typeof AdminRegistrationRoute
  AdminSpeechRoute: typeof AdminSpeechRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDesignRoute: AdminDesignRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLlmRoute: AdminLlmRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminPromptsRoute: AdminPromptsRoute,
  AdminRegistrationRoute: AdminRegistrationRoute,
  AdminSpeechRoute: AdminSpeechRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface URouteRouteChildren {
  UUsernameNoteSlugRoute: typeof UUsernameNoteSlugRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

const URouteRouteChildren: URouteRouteChildren = {
  UUsernameNoteSlugRoute: UUsernameNoteSlugRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}

const URouteRouteWithChildren =
  URouteRoute._addFileChildren(URouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  URouteRoute: URouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EmailChangeConfirmRoute: EmailChangeConfirmRoute,
  MediaMediaIdRoute: MediaMediaIdRoute,
  PasswordResetConfirmRoute: PasswordResetConfirmRoute,
  ShareTokenRoute: ShareTokenRoute,
  PasswordResetIndexRoute: PasswordResetIndexRoute,
  NotesPublicNoteIdRoute: NotesPublicNoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
