/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ViewsRouteRouteImport } from './routes/views/route'
import { Route as URouteRouteImport } from './routes/u/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ExportsRouteRouteImport } from './routes/exports/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as ViewsIndexRouteImport } from './routes/views/index'
import { Route as PasswordResetIndexRouteImport } from './routes/password-reset/index'
import { Route as ExportsIndexRouteImport } from './routes/exports/index'
import { Route as ExportIndexRouteImport } from './routes/export/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsPromptsRouteImport } from './routes/settings/prompts'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsAccountDeleteRouteImport } from './routes/settings/account-delete'
import { Route as PasswordResetConfirmRouteImport } from './routes/password-reset/confirm'
import { Route as MediaMediaIdRouteImport } from './routes/media/$mediaId'
import { Route as ExportsJobIdRouteImport } from './routes/exports/$jobId'
import { Route as EmailChangeConfirmRouteImport } from './routes/email-change/confirm'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRegistrationRouteImport } from './routes/admin/registration'
import { Route as AdminPromptsRouteImport } from './routes/admin/prompts'
import { Route as AdminMetricsRouteImport } from './routes/admin/metrics'
import { Route as AdminLlmRouteImport } from './routes/admin/llm'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminDesignRouteImport } from './routes/admin/design'
import { Route as UUsernameIndexRouteImport } from './routes/u/$username/index'
import { Route as AppUploadIndexRouteImport } from './routes/_app/upload/index'
import { Route as AppTrashIndexRouteImport } from './routes/_app/trash/index'
import { Route as AppTagsIndexRouteImport } from './routes/_app/tags/index'
import { Route as UUsernameNoteSlugRouteImport } from './routes/u/$username/$noteSlug'
import { Route as NotesPublicNoteIdRouteImport } from './routes/notes/public/$noteId'
import { Route as NotesNoteIdPublishRouteImport } from './routes/notes/$noteId/publish'
import { Route as NotesNoteIdExportRouteImport } from './routes/notes/$noteId/export'
import { Route as AppNotesNewRouteImport } from './routes/_app/notes/new'
import { Route as AppNotesNoteIdIndexRouteImport } from './routes/_app/notes/$noteId/index'
import { Route as AppNotesNoteIdEditRouteImport } from './routes/_app/notes/$noteId/edit'
import { Route as AppNotesNoteIdHistoryRouteRouteImport } from './routes/_app/notes/$noteId/history/route'
import { Route as AppNotesNoteIdHistoryIndexRouteImport } from './routes/_app/notes/$noteId/history/index'
import { Route as AppNotesNoteIdHistoryRevisionIdRouteImport } from './routes/_app/notes/$noteId/history/$revisionId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsRouteRoute = ViewsRouteRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => rootRouteImport,
} as any)
const URouteRoute = URouteRouteImport.update({
  id: '/u',
  path: '/u',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRouteRoute = ExportsRouteRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsIndexRoute = ViewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewsRouteRoute,
} as any)
const PasswordResetIndexRoute = PasswordResetIndexRouteImport.update({
  id: '/password-reset/',
  path: '/password-reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsIndexRoute = ExportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExportsRouteRoute,
} as any)
const ExportIndexRoute = ExportIndexRouteImport.update({
  id: '/export/',
  path: '/export/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPromptsRoute = SettingsPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccountDeleteRoute = SettingsAccountDeleteRouteImport.update({
  id: '/account-delete',
  path: '/account-delete',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PasswordResetConfirmRoute = PasswordResetConfirmRouteImport.update({
  id: '/password-reset/confirm',
  path: '/password-reset/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaMediaIdRoute = MediaMediaIdRouteImport.update({
  id: '/media/$mediaId',
  path: '/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsJobIdRoute = ExportsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ExportsRouteRoute,
} as any)
const EmailChangeConfirmRoute = EmailChangeConfirmRouteImport.update({
  id: '/email-change/confirm',
  path: '/email-change/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegistrationRoute = AdminRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromptsRoute = AdminPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLlmRoute = AdminLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDesignRoute = AdminDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => URouteRoute,
} as any)
const AppUploadIndexRoute = AppUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrashIndexRoute = AppTrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTagsIndexRoute = AppTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AppRouteRoute,
} as any)
const UUsernameNoteSlugRoute = UUsernameNoteSlugRouteImport.update({
  id: '/$username/$noteSlug',
  path: '/$username/$noteSlug',
  getParentRoute: () => URouteRoute,
} as any)
const NotesPublicNoteIdRoute = NotesPublicNoteIdRouteImport.update({
  id: '/notes/public/$noteId',
  path: '/notes/public/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdPublishRoute = NotesNoteIdPublishRouteImport.update({
  id: '/notes/$noteId/publish',
  path: '/notes/$noteId/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdExportRoute = NotesNoteIdExportRouteImport.update({
  id: '/notes/$noteId/export',
  path: '/notes/$noteId/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesNewRoute = AppNotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdIndexRoute = AppNotesNoteIdIndexRouteImport.update({
  id: '/notes/$noteId/',
  path: '/notes/$noteId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdEditRoute = AppNotesNoteIdEditRouteImport.update({
  id: '/notes/$noteId/edit',
  path: '/notes/$noteId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdHistoryRouteRoute =
  AppNotesNoteIdHistoryRouteRouteImport.update({
    id: '/notes/$noteId/history',
    path: '/notes/$noteId/history',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppNotesNoteIdHistoryIndexRoute =
  AppNotesNoteIdHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppNotesNoteIdHistoryRouteRoute,
  } as any)
const AppNotesNoteIdHistoryRevisionIdRoute =
  AppNotesNoteIdHistoryRevisionIdRouteImport.update({
    id: '/$revisionId',
    path: '/$revisionId',
    getParentRoute: () => AppNotesNoteIdHistoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/exports': typeof ExportsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/views': typeof ViewsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/registration': typeof AdminRegistrationRoute
  '/admin/users': typeof AdminUsersRoute
  '/email-change/confirm': typeof EmailChangeConfirmRoute
  '/exports/$jobId': typeof ExportsJobIdRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/settings/account-delete': typeof SettingsAccountDeleteRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/export/': typeof ExportIndexRoute
  '/exports/': typeof ExportsIndexRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/views/': typeof ViewsIndexRoute
  '/notes/new': typeof AppNotesNewRoute
  '/notes/$noteId/export': typeof NotesNoteIdExportRoute
  '/notes/$noteId/publish': typeof NotesNoteIdPublishRoute
  '/notes/public/$noteId': typeof NotesPublicNoteIdRoute
  '/u/$username/$noteSlug': typeof UUsernameNoteSlugRoute
  '/tags/': typeof AppTagsIndexRoute
  '/trash/': typeof AppTrashIndexRoute
  '/upload/': typeof AppUploadIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/notes/$noteId/history': typeof AppNotesNoteIdHistoryRouteRouteWithChildren
  '/notes/$noteId/edit': typeof AppNotesNoteIdEditRoute
  '/notes/$noteId/': typeof AppNotesNoteIdIndexRoute
  '/notes/$noteId/history/$revisionId': typeof AppNotesNoteIdHistoryRevisionIdRoute
  '/notes/$noteId/history/': typeof AppNotesNoteIdHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/registration': typeof AdminRegistrationRoute
  '/admin/users': typeof AdminUsersRoute
  '/email-change/confirm': typeof EmailChangeConfirmRoute
  '/exports/$jobId': typeof ExportsJobIdRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/settings/account-delete': typeof SettingsAccountDeleteRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/export': typeof ExportIndexRoute
  '/exports': typeof ExportsIndexRoute
  '/password-reset': typeof PasswordResetIndexRoute
  '/views': typeof ViewsIndexRoute
  '/notes/new': typeof AppNotesNewRoute
  '/notes/$noteId/export': typeof NotesNoteIdExportRoute
  '/notes/$noteId/publish': typeof NotesNoteIdPublishRoute
  '/notes/public/$noteId': typeof NotesPublicNoteIdRoute
  '/u/$username/$noteSlug': typeof UUsernameNoteSlugRoute
  '/tags': typeof AppTagsIndexRoute
  '/trash': typeof AppTrashIndexRoute
  '/upload': typeof AppUploadIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/notes/$noteId/edit': typeof AppNotesNoteIdEditRoute
  '/notes/$noteId': typeof AppNotesNoteIdIndexRoute
  '/notes/$noteId/history/$revisionId': typeof AppNotesNoteIdHistoryRevisionIdRoute
  '/notes/$noteId/history': typeof AppNotesNoteIdHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/exports': typeof ExportsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/u': typeof URouteRouteWithChildren
  '/views': typeof ViewsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/registration': typeof AdminRegistrationRoute
  '/admin/users': typeof AdminUsersRoute
  '/email-change/confirm': typeof EmailChangeConfirmRoute
  '/exports/$jobId': typeof ExportsJobIdRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/settings/account-delete': typeof SettingsAccountDeleteRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/export/': typeof ExportIndexRoute
  '/exports/': typeof ExportsIndexRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/views/': typeof ViewsIndexRoute
  '/_app/notes/new': typeof AppNotesNewRoute
  '/notes/$noteId/export': typeof NotesNoteIdExportRoute
  '/notes/$noteId/publish': typeof NotesNoteIdPublishRoute
  '/notes/public/$noteId': typeof NotesPublicNoteIdRoute
  '/u/$username/$noteSlug': typeof UUsernameNoteSlugRoute
  '/_app/tags/': typeof AppTagsIndexRoute
  '/_app/trash/': typeof AppTrashIndexRoute
  '/_app/upload/': typeof AppUploadIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/_app/notes/$noteId/history': typeof AppNotesNoteIdHistoryRouteRouteWithChildren
  '/_app/notes/$noteId/edit': typeof AppNotesNoteIdEditRoute
  '/_app/notes/$noteId/': typeof AppNotesNoteIdIndexRoute
  '/_app/notes/$noteId/history/$revisionId': typeof AppNotesNoteIdHistoryRevisionIdRoute
  '/_app/notes/$noteId/history/': typeof AppNotesNoteIdHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/exports'
    | '/settings'
    | '/u'
    | '/views'
    | '/about'
    | '/error'
    | '/login'
    | '/privacy'
    | '/search'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/design'
    | '/admin/jobs'
    | '/admin/llm'
    | '/admin/metrics'
    | '/admin/prompts'
    | '/admin/registration'
    | '/admin/users'
    | '/email-change/confirm'
    | '/exports/$jobId'
    | '/media/$mediaId'
    | '/password-reset/confirm'
    | '/settings/account-delete'
    | '/settings/profile'
    | '/settings/prompts'
    | '/settings/security'
    | '/share/$token'
    | '/admin/'
    | '/export/'
    | '/exports/'
    | '/password-reset/'
    | '/views/'
    | '/notes/new'
    | '/notes/$noteId/export'
    | '/notes/$noteId/publish'
    | '/notes/public/$noteId'
    | '/u/$username/$noteSlug'
    | '/tags/'
    | '/trash/'
    | '/upload/'
    | '/u/$username/'
    | '/notes/$noteId/history'
    | '/notes/$noteId/edit'
    | '/notes/$noteId/'
    | '/notes/$noteId/history/$revisionId'
    | '/notes/$noteId/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/u'
    | '/about'
    | '/error'
    | '/login'
    | '/privacy'
    | '/search'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/design'
    | '/admin/jobs'
    | '/admin/llm'
    | '/admin/metrics'
    | '/admin/prompts'
    | '/admin/registration'
    | '/admin/users'
    | '/email-change/confirm'
    | '/exports/$jobId'
    | '/media/$mediaId'
    | '/password-reset/confirm'
    | '/settings/account-delete'
    | '/settings/profile'
    | '/settings/prompts'
    | '/settings/security'
    | '/share/$token'
    | '/'
    | '/admin'
    | '/export'
    | '/exports'
    | '/password-reset'
    | '/views'
    | '/notes/new'
    | '/notes/$noteId/export'
    | '/notes/$noteId/publish'
    | '/notes/public/$noteId'
    | '/u/$username/$noteSlug'
    | '/tags'
    | '/trash'
    | '/upload'
    | '/u/$username'
    | '/notes/$noteId/edit'
    | '/notes/$noteId'
    | '/notes/$noteId/history/$revisionId'
    | '/notes/$noteId/history'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/exports'
    | '/settings'
    | '/u'
    | '/views'
    | '/about'
    | '/error'
    | '/login'
    | '/privacy'
    | '/search'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/design'
    | '/admin/jobs'
    | '/admin/llm'
    | '/admin/metrics'
    | '/admin/prompts'
    | '/admin/registration'
    | '/admin/users'
    | '/email-change/confirm'
    | '/exports/$jobId'
    | '/media/$mediaId'
    | '/password-reset/confirm'
    | '/settings/account-delete'
    | '/settings/profile'
    | '/settings/prompts'
    | '/settings/security'
    | '/share/$token'
    | '/_app/'
    | '/admin/'
    | '/export/'
    | '/exports/'
    | '/password-reset/'
    | '/views/'
    | '/_app/notes/new'
    | '/notes/$noteId/export'
    | '/notes/$noteId/publish'
    | '/notes/public/$noteId'
    | '/u/$username/$noteSlug'
    | '/_app/tags/'
    | '/_app/trash/'
    | '/_app/upload/'
    | '/u/$username/'
    | '/_app/notes/$noteId/history'
    | '/_app/notes/$noteId/edit'
    | '/_app/notes/$noteId/'
    | '/_app/notes/$noteId/history/$revisionId'
    | '/_app/notes/$noteId/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ExportsRouteRoute: typeof ExportsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  URouteRoute: typeof URouteRouteWithChildren
  ViewsRouteRoute: typeof ViewsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EmailChangeConfirmRoute: typeof EmailChangeConfirmRoute
  MediaMediaIdRoute: typeof MediaMediaIdRoute
  PasswordResetConfirmRoute: typeof PasswordResetConfirmRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ExportIndexRoute: typeof ExportIndexRoute
  PasswordResetIndexRoute: typeof PasswordResetIndexRoute
  NotesNoteIdExportRoute: typeof NotesNoteIdExportRoute
  NotesNoteIdPublishRoute: typeof NotesNoteIdPublishRoute
  NotesPublicNoteIdRoute: typeof NotesPublicNoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views': {
      id: '/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof ViewsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u': {
      id: '/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof URouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views/': {
      id: '/views/'
      path: '/'
      fullPath: '/views/'
      preLoaderRoute: typeof ViewsIndexRouteImport
      parentRoute: typeof ViewsRouteRoute
    }
    '/password-reset/': {
      id: '/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset/'
      preLoaderRoute: typeof PasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports/': {
      id: '/exports/'
      path: '/'
      fullPath: '/exports/'
      preLoaderRoute: typeof ExportsIndexRouteImport
      parentRoute: typeof ExportsRouteRoute
    }
    '/export/': {
      id: '/export/'
      path: '/export'
      fullPath: '/export/'
      preLoaderRoute: typeof ExportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/prompts': {
      id: '/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof SettingsPromptsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/account-delete': {
      id: '/settings/account-delete'
      path: '/account-delete'
      fullPath: '/settings/account-delete'
      preLoaderRoute: typeof SettingsAccountDeleteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/password-reset/confirm': {
      id: '/password-reset/confirm'
      path: '/password-reset/confirm'
      fullPath: '/password-reset/confirm'
      preLoaderRoute: typeof PasswordResetConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$mediaId': {
      id: '/media/$mediaId'
      path: '/media/$mediaId'
      fullPath: '/media/$mediaId'
      preLoaderRoute: typeof MediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports/$jobId': {
      id: '/exports/$jobId'
      path: '/$jobId'
      fullPath: '/exports/$jobId'
      preLoaderRoute: typeof ExportsJobIdRouteImport
      parentRoute: typeof ExportsRouteRoute
    }
    '/email-change/confirm': {
      id: '/email-change/confirm'
      path: '/email-change/confirm'
      fullPath: '/email-change/confirm'
      preLoaderRoute: typeof EmailChangeConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration': {
      id: '/admin/registration'
      path: '/registration'
      fullPath: '/admin/registration'
      preLoaderRoute: typeof AdminRegistrationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/prompts': {
      id: '/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminPromptsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/llm': {
      id: '/admin/llm'
      path: '/llm'
      fullPath: '/admin/llm'
      preLoaderRoute: typeof AdminLlmRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/design': {
      id: '/admin/design'
      path: '/design'
      fullPath: '/admin/design'
      preLoaderRoute: typeof AdminDesignRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof URouteRoute
    }
    '/_app/upload/': {
      id: '/_app/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof AppUploadIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/trash/': {
      id: '/_app/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof AppTrashIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tags/': {
      id: '/_app/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AppTagsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/u/$username/$noteSlug': {
      id: '/u/$username/$noteSlug'
      path: '/$username/$noteSlug'
      fullPath: '/u/$username/$noteSlug'
      preLoaderRoute: typeof UUsernameNoteSlugRouteImport
      parentRoute: typeof URouteRoute
    }
    '/notes/public/$noteId': {
      id: '/notes/public/$noteId'
      path: '/notes/public/$noteId'
      fullPath: '/notes/public/$noteId'
      preLoaderRoute: typeof NotesPublicNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId/publish': {
      id: '/notes/$noteId/publish'
      path: '/notes/$noteId/publish'
      fullPath: '/notes/$noteId/publish'
      preLoaderRoute: typeof NotesNoteIdPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId/export': {
      id: '/notes/$noteId/export'
      path: '/notes/$noteId/export'
      fullPath: '/notes/$noteId/export'
      preLoaderRoute: typeof NotesNoteIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notes/new': {
      id: '/_app/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AppNotesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId/': {
      id: '/_app/notes/$noteId/'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId/'
      preLoaderRoute: typeof AppNotesNoteIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId/edit': {
      id: '/_app/notes/$noteId/edit'
      path: '/notes/$noteId/edit'
      fullPath: '/notes/$noteId/edit'
      preLoaderRoute: typeof AppNotesNoteIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId/history': {
      id: '/_app/notes/$noteId/history'
      path: '/notes/$noteId/history'
      fullPath: '/notes/$noteId/history'
      preLoaderRoute: typeof AppNotesNoteIdHistoryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId/history/': {
      id: '/_app/notes/$noteId/history/'
      path: '/'
      fullPath: '/notes/$noteId/history/'
      preLoaderRoute: typeof AppNotesNoteIdHistoryIndexRouteImport
      parentRoute: typeof AppNotesNoteIdHistoryRouteRoute
    }
    '/_app/notes/$noteId/history/$revisionId': {
      id: '/_app/notes/$noteId/history/$revisionId'
      path: '/$revisionId'
      fullPath: '/notes/$noteId/history/$revisionId'
      preLoaderRoute: typeof AppNotesNoteIdHistoryRevisionIdRouteImport
      parentRoute: typeof AppNotesNoteIdHistoryRouteRoute
    }
  }
}

interface AppNotesNoteIdHistoryRouteRouteChildren {
  AppNotesNoteIdHistoryRevisionIdRoute: typeof AppNotesNoteIdHistoryRevisionIdRoute
  AppNotesNoteIdHistoryIndexRoute: typeof AppNotesNoteIdHistoryIndexRoute
}

const AppNotesNoteIdHistoryRouteRouteChildren: AppNotesNoteIdHistoryRouteRouteChildren =
  {
    AppNotesNoteIdHistoryRevisionIdRoute: AppNotesNoteIdHistoryRevisionIdRoute,
    AppNotesNoteIdHistoryIndexRoute: AppNotesNoteIdHistoryIndexRoute,
  }

const AppNotesNoteIdHistoryRouteRouteWithChildren =
  AppNotesNoteIdHistoryRouteRoute._addFileChildren(
    AppNotesNoteIdHistoryRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppNotesNewRoute: typeof AppNotesNewRoute
  AppTagsIndexRoute: typeof AppTagsIndexRoute
  AppTrashIndexRoute: typeof AppTrashIndexRoute
  AppUploadIndexRoute: typeof AppUploadIndexRoute
  AppNotesNoteIdHistoryRouteRoute: typeof AppNotesNoteIdHistoryRouteRouteWithChildren
  AppNotesNoteIdEditRoute: typeof AppNotesNoteIdEditRoute
  AppNotesNoteIdIndexRoute: typeof AppNotesNoteIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppNotesNewRoute: AppNotesNewRoute,
  AppTagsIndexRoute: AppTagsIndexRoute,
  AppTrashIndexRoute: AppTrashIndexRoute,
  AppUploadIndexRoute: AppUploadIndexRoute,
  AppNotesNoteIdHistoryRouteRoute: AppNotesNoteIdHistoryRouteRouteWithChildren,
  AppNotesNoteIdEditRoute: AppNotesNoteIdEditRoute,
  AppNotesNoteIdIndexRoute: AppNotesNoteIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminDesignRoute: typeof AdminDesignRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLlmRoute: typeof AdminLlmRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminPromptsRoute: typeof AdminPromptsRoute
  AdminRegistrationRoute: typeof AdminRegistrationRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDesignRoute: AdminDesignRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLlmRoute: AdminLlmRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminPromptsRoute: AdminPromptsRoute,
  AdminRegistrationRoute: AdminRegistrationRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ExportsRouteRouteChildren {
  ExportsJobIdRoute: typeof ExportsJobIdRoute
  ExportsIndexRoute: typeof ExportsIndexRoute
}

const ExportsRouteRouteChildren: ExportsRouteRouteChildren = {
  ExportsJobIdRoute: ExportsJobIdRoute,
  ExportsIndexRoute: ExportsIndexRoute,
}

const ExportsRouteRouteWithChildren = ExportsRouteRoute._addFileChildren(
  ExportsRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAccountDeleteRoute: typeof SettingsAccountDeleteRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsPromptsRoute: typeof SettingsPromptsRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccountDeleteRoute: SettingsAccountDeleteRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsPromptsRoute: SettingsPromptsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface URouteRouteChildren {
  UUsernameNoteSlugRoute: typeof UUsernameNoteSlugRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

const URouteRouteChildren: URouteRouteChildren = {
  UUsernameNoteSlugRoute: UUsernameNoteSlugRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}

const URouteRouteWithChildren =
  URouteRoute._addFileChildren(URouteRouteChildren)

interface ViewsRouteRouteChildren {
  ViewsIndexRoute: typeof ViewsIndexRoute
}

const ViewsRouteRouteChildren: ViewsRouteRouteChildren = {
  ViewsIndexRoute: ViewsIndexRoute,
}

const ViewsRouteRouteWithChildren = ViewsRouteRoute._addFileChildren(
  ViewsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ExportsRouteRoute: ExportsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  URouteRoute: URouteRouteWithChildren,
  ViewsRouteRoute: ViewsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EmailChangeConfirmRoute: EmailChangeConfirmRoute,
  MediaMediaIdRoute: MediaMediaIdRoute,
  PasswordResetConfirmRoute: PasswordResetConfirmRoute,
  ShareTokenRoute: ShareTokenRoute,
  ExportIndexRoute: ExportIndexRoute,
  PasswordResetIndexRoute: PasswordResetIndexRoute,
  NotesNoteIdExportRoute: NotesNoteIdExportRoute,
  NotesNoteIdPublishRoute: NotesNoteIdPublishRoute,
  NotesPublicNoteIdRoute: NotesPublicNoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
