export const NoteErrorCode = {
  InvalidId: "note_invalid_id",
  SlugEmpty: "note_slug_empty",
  SlugTooLong: "note_slug_too_long",
  InvalidSlug: "note_invalid_slug",
  TitleEmpty: "note_title_empty",
  TitleTooLong: "note_title_too_long",
  ContentTooLarge: "content_too_large",
  InvalidStatus: "note_invalid_status",
  FrontMatterKeyInvalid: "note_front_matter_key_invalid",
  FrontMatterTooDeep: "note_front_matter_too_deep",
  FrontMatterTooLarge: "note_front_matter_too_large",
  FrontMatterInvalidValue: "note_front_matter_invalid_value",
  InternalLinkInvalidKind: "note_internal_link_invalid_kind",
  InternalLinkInvalidTarget: "note_internal_link_invalid_target",
  EditLockInvalidExpiry: "note_edit_lock_invalid_expiry",
  EditLockTtlTooLong: "note_edit_lock_ttl_too_long",
  EditLockedByOther: "edit_locked_by_other",
  CannotMoveTrashed: "note_cannot_move_trashed",
  Trashed: "note_trashed",
  AlreadyTrashed: "note_already_trashed",
  NotTrashed: "note_not_trashed",
  SlugConflict: "slug_conflict",
  ReleaseNotOwner: "note_release_not_owner",
  ExtendNotOwner: "note_extend_not_owner",
  MediaNotOwned: "media_not_owned",
  InvalidRevisionId: "note_invalid_revision_id",
} as const;

export type NoteErrorCode = (typeof NoteErrorCode)[keyof typeof NoteErrorCode];
